%%
%% Autogenerated by Thrift
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(test_types).

-include("test_types.hrl").

-export([struct_info/1]).
struct_info('i am a dummy struct') -> undefined.
