/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef Test_CONSTANTS_H
#define Test_CONSTANTS_H

#include "Test_types.h"

namespace test {

class TestConstants {
 public:
  TestConstants();

};

extern const TestConstants g_Test_constants;

} // namespace

#endif
