/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "Test_constants.h"

namespace test {

const TestConstants g_Test_constants;

TestConstants::TestConstants() {
}

} // namespace

